# =================================================
# PostgreSQL 接続設定 (Render)
# =================================================
# External Connection String が "postgresql://user:pass@host:port/db" なら
# 下記のように "jdbc:postgresql://host:port/db" の形式で書くよ！
spring.datasource.url=jdbc:postgresql://dpg-d7510pkhg0os73aam0l0-a:5432/PortfolioDB
spring.datasource.username=portfolio_db_xr1z_user
spring.datasource.password=9UIc2Tj4cgkpvr3nzfr79AqGzbJqqb2H
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate の設定
# update にしておくと、Javaで作ったEntityに合わせてテーブルを自動で作ってくれるよ！
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =================================================
# サーバー設定
# =================================================
server.port=8080
server.servlet.session.cookie.same-site=strict
server.servlet.session.timeout=30m